
about :

  name : "wStarter"
  description : "Collection of tools to generate background service to start and pack application. Starter consists of 3 pieces, maker - generating code for run-time, client run-time piece, and server run-time piece. Use the module to keep files structure of the application and make code aware wherein the file system is it executed."
  version : "0.3.49"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wStarter.git
  bugs : https://github.com/Wandalen/wStarter/issues

step :

  export.proto :
    inherit : predefined.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

